name: CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.platform }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        generator:
          - Ninja
          - Xcode
        configuration: [Debug, Release]
        include:
          - generator: Ninja
            platform: Linux
            os: ubuntu-latest
          - generator: Xcode
            platform: macOS
            os: macos-latest

    steps:
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install build-essential g++ cmake ninja-build libsdl2-dev
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        env:
          HOMEBREW_NO_ANALYTICS: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        run: |
          brew update
          brew install sdl2
      - uses: actions/checkout@v3
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G ${{ matrix.generator }} ..
          cmake --build .
