name: Build Snapshot Release

on:
    workflow_dispatch:
#on:
#  push:
#    tags:
#      - "v*"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-SDL2
    - uses: actions/checkout@v2
    - name: build
      run: |
        mkdir build
        cd build
        cmake -G 'MSYS Makefiles' ..
        make
        zip goattrk2-${{ github.ref }}.zip goattrk2.exe
#    - name: Upload Release Binary
#    - uses: svenstaro/upload-release-action@v1-release
#      with:
#        repo_token: ${{ secrets.GITHUB_TOKEN }}
#        file: build/goattrk2.exe
#        tag: ${{ github.ref }}
#        file_glob: true
#        overwrite: true
