name: Build Snapshot Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          zip
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-SDL2
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'libsidplayfp/libresidfp'
        regex: true
        file: "libresidfp-.*\\.tar\\.gz"
        target: 'subdir/'
    - name: build-lib
      run: |
        cd subdir
        export LDFLAGS="-s -Wl,-no-undefined -Wl,-O1 -static"
        export CXXFLAGS="-O2 -march=x86-64 -fomit-frame-pointer -pipe"
        export PKG_CONFIG="pkg-config --static"
        tar -xf libresidfp*.tar.gz
        cd libresidfp*/.
        ./configure --disable-dependency-tracking --disable-shared --enable-static --with-simd=runtime
        make && make install
    - uses: actions/checkout@v6)
      with:
        ref: ${{ github.ref }}
    - name: Get the tag name
      id: get_tag_name
      run: echo "tagname=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    - name: build
      run: |
        mkdir build
        cd build
        cmake -G 'MSYS Makefiles' -DCMAKE_BUILD_TYPE=Release -DSTATIC=ON ..
        cmake --build .
        cp ../readme.* ../authors ../copying ../goat_tracker_commands.pdf .
        zip gt2-unofficial_build-${{ steps.get_tag_name.outputs.tagname }}.zip *.exe readme.* authors copying goat_tracker_commands.pdf
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/gt2-unofficial_build-${{ steps.get_tag_name.outputs.tagname }}.zip
        tag: ${{ github.ref }}
        file_glob: true
        overwrite: true
